// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyofrbpibmwcvgmzvhhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5b2ZyYnBpYm13Y3ZnbXp2aGhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2ODA3NjEsImV4cCI6MjA0OTI1Njc2MX0.s6J9qyjEgf2q6qotR6jEdGCkQTKLdTNKQEu4_OkPDKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);